site_name: SuperBank
site_url: https://teknekt.github.io/superbank-docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

repo_url: https://github.com/Teknekt/superbank-docs

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Plugin Spec: plugin-spec.md
  - Sidecar Schema: sidecar-schema.md
  - Pack Anatomy: pack-anatomy.md
  - Profiles: profiles.md
